apiVersion: webserver-helm.mklug.at/v1alpha1
kind: Nginx
metadata:
  name: nginx-sample
spec:
  replicas: 1
  image: nginx
  mesage: "<h1>hello from the helm operator</h1>"
  ingress:
    enabled: true
    hostname: nginx.example.com