{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  rules:
    - host: {{ required "if ingress is enabled a hostname is requiered (ingress.hostname)" .Values.ingress.hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}
              servicePort: "http"
  {{- end }}
